### ISSUE TITLE
Folders which end with a period and a character (e.g "1.0") do not count as a folder

### ISSUE THREAD

**Issue by vys534** [RoanH/ImageScaler#3]
![image](https://user-images.githubusercontent.com/77179954/128615922-458a471d-6c7f-45a4-8c7e-21513b74bf97.png)

Manually setting the input folder is a workaround for this issue.

**Comment by RoanH** [comment]
Oh, that's an interesting oversight, I'm guessing I forgot that folder names can contain periods, thanks for the report!

**Comment by RoanH** [comment]
Fixed in v2.5 which I'll release in a bit.
